version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mern-network

  server:
    build:
      context: ./server
    container_name: mern-server
    environment:
      - MONGO_URI=mongodb://mongodb:27017/yourdb
    ports:
      - "8800:8800"
    networks:
      - mern-network
    depends_on:
      - mongodb

  web-app:
    build:
      context: ./web-app
    container_name: mern-web-app
    ports:
      - "3000:80"
    networks:
      - mern-network
    depends_on:
      - server

networks:
  mern-network:
    driver: bridge
