apiVersion: v1
kind: Service
metadata:
  name: mern-server-service
spec:
  type: NodePort
  selector:
    app: mern-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8800
    nodePort: 30002