# templates/mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
type: Opaque
data:
  MONGO_USERNAME: {{ user1| b64enc }}
  MONGO_PASSWORD: {{ root | b64enc }}
  MONGO_DATABASE: {{ examdatabase | b64enc }}